AkciqApp/Controllers/PersonalInfoController.cs
namespace AkciqApp.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AkciqApp.Services.EmailService;
    using Microsoft.AspNetCore.Mvc;

    public class PersonalInfoController : Controller
    {
        public PersonalInfoController(IEmailService emailService)
        {
        }

        public IActionResult Contact() => this.View();
    }
}

AkciqApp/Views/Shared/HandleError.cshtml
@{
    ViewData["Title"] = "HandleError";
}

    <h1>@ViewData["ErrorMessage"]</h1>

AkciqApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gas prices</title>

    <meta name="title" content="fuel prices." />
    <meta name="description" content="fuel prices in bulgaria." />
    <meta name="keywords" content="Цени на горивата, българиа, горива, градове, град, бензин, дизел, пропан бутан, метан, fuel prices" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body class="">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gas prices</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a asp-area="" asp-controller="PersonalInfo" asp-action="Contact" class="nav-link text-dark">For contact</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* Cookie consent *@
    <div id="cookieConsents"></div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex">
            <div class="text-left">
                &copy; 2020 - Gas prices - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>

            <div class="text-right w-100">
                <a asp-area="" asp-controller="PersonalInfo" asp-action="Contact" style="text-decoration:none;">For contact</a>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/cookieConsent.js" asp-append-version="true"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>